#!/bin/sh

# --- Block direct commits to develop ---
branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ]; then
  echo "❌ Direct commits to 'main' branch are not allowed. Use a another branch."
  exit 1
fi

# --- Get staged JS/TS/CSS/SCSS files ---
files=$(git diff --cached --name-only --diff-filter=AMCR -- '*.js' '*.jsx' '*.ts' '*.tsx' '*.css' '*.scss')

if [ -z "$files" ]; then
  echo "✅ No files staged for commit."
  exit 0
fi

echo "🚀 Running ESLint and Prettier checks..."

# --- Run ESLint (using npm script) ---
echo "Checking with ESLint..."
if ! npm run lint; then
  echo "❌ ESLint failed. Please fix issues or run: npm run lint:fix"
  exit 1
else
 echo "✅ ESlint is Success."
fi

# --- Run Prettier check (using npm script) ---
echo "Checking format with Prettier..."
if ! npm run format:check; then
  echo "❌ Prettier check failed. Please run: npm run format"
  exit 1
else
  echo "✅ Prettier check failed. Please run: npm run format"
fi

echo "✅ ESLint and Prettier passed!"
exit 0
